name: Auto-update Scoop Bucket Manifests

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  checkver:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Scoop Checkver
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
